export type StoreRecord = {
  id: string;
  storeName: string;
  categoryLargeName: string;
  categoryMediumName: string;
  categorySmallName: string;
  sido: string;
  sigungu: string;
  dong: string;
  address: string;
};

export const mockStores: StoreRecord[] = [
  {
    id: "store-001",
    storeName: "연남브루 커피",
    categoryLargeName: "음식",
    categoryMediumName: "카페",
    categorySmallName: "커피전문점",
    sido: "서울특별시",
    sigungu: "마포구",
    dong: "연남동",
    address: "서울특별시 마포구 동교로 245",
  },
  {
    id: "store-002",
    storeName: "망원 생활식당",
    categoryLargeName: "음식",
    categoryMediumName: "한식",
    categorySmallName: "백반",
    sido: "서울특별시",
    sigungu: "마포구",
    dong: "망원동",
    address: "서울특별시 마포구 월드컵로 87",
  },
  {
    id: "store-003",
    storeName: "합정 문구랩",
    categoryLargeName: "소매",
    categoryMediumName: "생활용품",
    categorySmallName: "문구점",
    sido: "서울특별시",
    sigungu: "마포구",
    dong: "합정동",
    address: "서울특별시 마포구 독막로 18",
  },
  {
    id: "store-004",
    storeName: "서교 헤어스튜디오",
    categoryLargeName: "생활서비스",
    categoryMediumName: "미용",
    categorySmallName: "미용실",
    sido: "서울특별시",
    sigungu: "마포구",
    dong: "서교동",
    address: "서울특별시 마포구 양화로 112",
  },
  {
    id: "store-005",
    storeName: "공덕 프레시마켓",
    categoryLargeName: "소매",
    categoryMediumName: "종합소매",
    categorySmallName: "슈퍼마켓",
    sido: "서울특별시",
    sigungu: "마포구",
    dong: "공덕동",
    address: "서울특별시 마포구 마포대로 122",
  },
  {
    id: "store-006",
    storeName: "성수 피트니스 클럽",
    categoryLargeName: "생활서비스",
    categoryMediumName: "스포츠",
    categorySmallName: "헬스장",
    sido: "서울특별시",
    sigungu: "성동구",
    dong: "성수동",
    address: "서울특별시 성동구 아차산로 96",
  },
  {
    id: "store-007",
    storeName: "성수 베이커리",
    categoryLargeName: "음식",
    categoryMediumName: "제과",
    categorySmallName: "베이커리",
    sido: "서울특별시",
    sigungu: "성동구",
    dong: "성수동",
    address: "서울특별시 성동구 연무장길 24",
  },
  {
    id: "store-008",
    storeName: "해운대 오션치킨",
    categoryLargeName: "음식",
    categoryMediumName: "치킨",
    categorySmallName: "치킨전문점",
    sido: "부산광역시",
    sigungu: "해운대구",
    dong: "우동",
    address: "부산광역시 해운대구 해운대로 620",
  },
  {
    id: "store-009",
    storeName: "수영 리빙편의점",
    categoryLargeName: "소매",
    categoryMediumName: "종합소매",
    categorySmallName: "편의점",
    sido: "부산광역시",
    sigungu: "수영구",
    dong: "광안동",
    address: "부산광역시 수영구 광안해변로 181",
  },
  {
    id: "store-010",
    storeName: "대전 둔산 메디컬",
    categoryLargeName: "의료",
    categoryMediumName: "병원",
    categorySmallName: "내과",
    sido: "대전광역시",
    sigungu: "서구",
    dong: "둔산동",
    address: "대전광역시 서구 둔산로 77",
  },
  {
    id: "store-011",
    storeName: "광주 충장 서점",
    categoryLargeName: "소매",
    categoryMediumName: "문화용품",
    categorySmallName: "서점",
    sido: "광주광역시",
    sigungu: "동구",
    dong: "충장로",
    address: "광주광역시 동구 충장로 45",
  },
  {
    id: "store-012",
    storeName: "대구 동성로 스터디",
    categoryLargeName: "교육",
    categoryMediumName: "학원",
    categorySmallName: "스터디카페",
    sido: "대구광역시",
    sigungu: "중구",
    dong: "동성로",
    address: "대구광역시 중구 동성로 21",
  },
];
